version: '2.2'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes: 
      - certs:/certs:nocopy
      - .:/usr/share/elasticsearch/config/certificates 

volumes: 
  certs:
    driver: local
    driver_opts:
       type: nfs4
       o: addr=10.0.0.145,rw
       device: ":/mnt/md0/es_certs"

networks:
  default:
    external:
      name: shared_network