version: '3.4'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: create_certs
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes: 
      - type: volume
        source: certs
        target: /certs
      - type: bind
        source: .
        target: /usr/share/elasticsearch/config/certificates

volumes: 
  certs:

networks:
  default:
    external:
      name: shared_network