version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - type: volume
        source: nginx_proxy_manager_data
        target: /data
        volume:
          nocopy: true
      - type: volume
        source: nginx_proxy_manager_letsencrypt
        target: /etc/letsencrypt
        volume:
          nocopy: true
    # depends_on:
    #   - db
  # db:
  #   image: 'jc21/mariadb-aria:latest'
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  #     MYSQL_DATABASE: '${MYSQL_DATABASE}'
  #     MYSQL_USER: '${MYSQL_USER}'
  #     MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
  #   volumes:
  #     - type: volume
  #       source: nginx_proxy_manager_mysql
  #       target: /var/lib/mysql
  #       volume:
  #         nocopy: true

volumes:
  nginx_proxy_manager_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=10.0.0.145,rw
      device: ":/mnt/md0/nginx_proxy_manager_data"
  nginx_proxy_manager_letsencrypt:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=10.0.0.145,rw
      device: ":/mnt/md0/nginx_proxy_manager_data"
  # nginx_proxy_manager_mysql:
  #   driver: local
  #   driver_opts:
  #     type: nfs4
  #     o: addr=10.0.0.145,rw
  #     device: ":/mnt/md0/nginx_proxy_manager_mysql"

networks:
  default:
    external:
      name: shared_network
